spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: AIGOU_CONSUMER
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7777/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8001

---
spring:
  profiles: test
  application:
    name: AIGOU_CONSUMER
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7777/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8003